# Generated by Django 5.2.3 on 2025-11-24 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'estado_sensor',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_invitacion', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tipo_sensor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('DEBUG', 'Depuración')], max_length=10)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='main.familia')),
            ],
            options={
                'db_table': 'planta',
            },
        ),
        migrations.CreateModel(
            name='PrediccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('confianza', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='main.planta')),
            ],
            options={
                'db_table': 'prediccion_ia',
            },
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion', models.IntegerField(help_text='Duración en segundos')),
                ('cantidad_agua', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad en ml', max_digits=8, null=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to='main.planta')),
            ],
            options={
                'db_table': 'riego',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estadosensor')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='main.planta')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tiposensor')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencias', models.JSONField(default=dict)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion',
                'unique_together': {('usuario',)},
            },
        ),
        migrations.CreateModel(
            name='FamiliaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('es_administrador', models.BooleanField(default=False)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='main.familia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('familia', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(default='info', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_e1341a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEstadoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='main.planta')),
            ],
            options={
                'db_table': 'seguimiento_estado_planta',
                'indexes': [models.Index(fields=['planta', 'fecha_registro'], name='seguimiento_planta__1ca900_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='main.sensor')),
            ],
            options={
                'db_table': 'medicion',
                'indexes': [models.Index(fields=['sensor', 'fecha'], name='medicion_sensor__3d5567_idx')],
            },
        ),
    ]
