# Generated by Django 5.2.3 on 2025-11-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usuario_reset_password_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='cantidad_plantas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familiausuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familiausuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rol'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='familiausuario',
            table='familia_usuario',
        ),
    ]
