# Generated by Django 5.2.3 on 2025-12-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_familia_cantidad_plantas_familiausuario_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='nombre',
            new_name='nombrePersonalizado',
        ),
        migrations.AddField(
            model_name='planta',
            name='aspecto',
            field=models.CharField(choices=[('normal', 'Normal'), ('floreciendo', 'Floreciendo'), ('con_frutos', 'Con Frutos'), ('hojas_amarillas', 'Hojas Amarillas'), ('crecimiento_lento', 'Crecimiento Lento'), ('exuberante', 'Exuberante')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='planta',
            name='estado',
            field=models.CharField(choices=[('saludable', 'Saludable'), ('necesita_agua', 'Necesita Agua'), ('peligro', 'En Peligro'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='planta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='plantas/'),
        ),
    ]
