# Generated by Django 5.2.3 on 2025-12-08 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_nombre_planta_nombrepersonalizado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediccionia',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Predicción de IA', 'verbose_name_plural': 'Predicciones de IA'},
        ),
        migrations.AddField(
            model_name='prediccionia',
            name='accion_sugerida',
            field=models.TextField(blank=True, help_text='Acción concreta que sugiere el sistema'),
        ),
        migrations.AddField(
            model_name='prediccionia',
            name='ejecutada_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se ejecutó la acción sugerida', null=True),
        ),
        migrations.AddField(
            model_name='prediccionia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADA', 'Ejecutada'), ('DESCARTADA', 'Descartada'), ('ACERTADA', 'Acertada'), ('ERRONEA', 'Errónea')], db_index=True, default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='prediccionia',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON'),
        ),
        migrations.AddField(
            model_name='prediccionia',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_index=True, default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='prediccionia',
            name='razon',
            field=models.TextField(blank=True, help_text='Explicación del porqué de la recomendación'),
        ),
        migrations.AddField(
            model_name='prediccionia',
            name='tipo',
            field=models.CharField(choices=[('CHAT', 'Chatbot'), ('RIEGO', 'Recomendación de Riego'), ('TEMPERATURA', 'Control de Temperatura'), ('HUMEDAD', 'Control de Humedad'), ('FERTILIZACION', 'Recomendación de Fertilización'), ('PLAGAS', 'Detección de Plagas'), ('CRECIMIENTO', 'Predicción de Crecimiento')], db_index=True, default='RIEGO', max_length=50),
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='confianza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddIndex(
            model_name='prediccionia',
            index=models.Index(fields=['-fecha_creacion'], name='prediccione_fecha_c_2f0298_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccionia',
            index=models.Index(fields=['estado', 'prioridad'], name='prediccione_estado_1a035c_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccionia',
            index=models.Index(fields=['planta', 'tipo'], name='prediccione_planta__a56b6a_idx'),
        ),
        migrations.AlterModelTable(
            name='prediccionia',
            table='predicciones_ia',
        ),
    ]
