# Generated by Django 5.2.3 on 2025-12-15 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_prediccionia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoestadoplanta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='seguimientos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='seguimientoestadoplanta',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='seguimientos/miniaturas/%Y/%m/%d/'),
        ),
    ]
