# Generated by Django 5.2.3 on 2025-12-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seguimientoestadoplanta_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('CRITICA', 'Crítica - Riego inmediato'), ('ADVERTENCIA', 'Advertencia - Monitorear'), ('INFO', 'Información - Todo normal')], default='ADVERTENCIA', max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='main.planta')),
                ('sensor_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='main.sensor')),
            ],
            options={
                'db_table': 'alerta_planta',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['planta', 'resuelta', 'fecha_creacion'], name='alerta_plan_planta__a699df_idx'), models.Index(fields=['tipo_alerta'], name='alerta_plan_tipo_al_cef8d3_idx')],
            },
        ),
    ]
