# Generated by Django 5.2.3 on 2026-01-03 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alertaplanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Modelo IA', max_length=100)),
                ('plant_id', models.IntegerField(default=0)),
                ('model_type', models.CharField(choices=[('RANDOM_FOREST', 'Random Forest'), ('GRADIENT_BOOSTING', 'Gradient Boosting'), ('NEURAL_NET', 'Neural Network')], default='RANDOM_FOREST', max_length=50)),
                ('accuracy', models.FloatField(default=0.0)),
                ('last_trained', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_file', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de IA',
                'verbose_name_plural': 'Modelos de IA',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=100, unique=True)),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Entrenando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='COMPLETED', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('samples_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
            },
        ),
        migrations.AlterModelOptions(
            name='riego',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='riego',
            name='cantidad_agua',
        ),
        migrations.RemoveField(
            model_name='riego',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='riego',
            name='fecha',
        ),
        migrations.AddField(
            model_name='alertaplanta',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alertaplanta',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertaplanta',
            name='notificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertaplanta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riego',
            name='cantidad_ml',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='riego',
            name='duracion_segundos',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='riego',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error')], default='PROGRAMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='riego',
            name='exito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riego',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='humedad_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='humedad_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='mensaje_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riego',
            name='tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual - Usuario'), ('AUTOMATICO', 'Automático - Programa'), ('IA', 'IA - Predicción automática'), ('EMERGENCIA', 'Emergencia - Alerta')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='riego',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertaplanta',
            name='tipo_alerta',
            field=models.CharField(choices=[('CRITICA', 'Crítica - Riego inmediato'), ('ADVERTENCIA', 'Advertencia - Monitorear'), ('INFO', 'Información - Todo normal'), ('EXITO', 'Éxito - Acción completada')], default='ADVERTENCIA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alertaplanta',
            index=models.Index(fields=['usuario', 'leida'], name='alerta_plan_usuario_f148c4_idx'),
        ),
        migrations.AddIndex(
            model_name='riego',
            index=models.Index(fields=['planta', 'fecha_creacion'], name='riego_planta__3cd65d_idx'),
        ),
        migrations.AddIndex(
            model_name='riego',
            index=models.Index(fields=['estado', 'fecha_programada'], name='riego_estado_86b243_idx'),
        ),
        migrations.AddIndex(
            model_name='riego',
            index=models.Index(fields=['usuario', 'tipo'], name='riego_usuario_918dd9_idx'),
        ),
    ]
